[package]
name = "music-visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"	
ctrlc = "3.2.1"
nannou = "0.18.1"
rustfft = "6.1.0"
